### ISSUE TITLE
Theme :)

### ISSUE THREAD

**Issue by NazmusSayad** [dzhavat/bracket-pair-toggler#1]
Bro which theme are you using here?
![image](https://github.com/dzhavat/bracket-pair-toggler/assets/87106526/5deb7f0d-d2af-4903-b854-5739f18f9720)

**Comment by dzhavat** [comment]
Hey @NazmusSayad 

Good question. The theme in that screenshot is from almost 2 years ago, and many themes have adjusted their colors since then. So it's kind of hard to tell with 100% certainty. 

I usually stick with built-in themes, so I'd say that the one above is "Dark (Visual Studio)". Hope that helps you :)

**Comment by NazmusSayad** [comment]
> Hey @NazmusSayad 
> 
> Good question. The theme in that screenshot is from almost 2 years ago, and many themes have adjusted their colors since then. So it's kind of hard to tell with 100% certainty. 
> 
> I usually stick with built-in themes, so I'd say that the one above is "Dark (Visual Studio)". Hope that helps you :)

I just liked the brackets color there 😅

**Comment by dzhavat** [comment]
Right now I'm using the built-in "Dark Modern" theme. Slightly updated "Dark (Visual Studio)". But there are hundreds of themes to choose from, so that's not an easy task 😅
